config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'maps#index'

  resources :rooms do
    resources :messages
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'users', to: 'devise/sessions#new'
  end

  post 'user/:id/', to: 'users#create'
  post 'user/:id/follow', to: 'users#follow', as: 'follow'
  post 'user/:id/unfollow', to: 'users#unfollow', as: 'unfollow'
  post 'user/:id/accept', to: 'users#accept', as: 'accept'
  post 'user/:id/decline', to: 'users#decline', as: 'decline'
  post 'user/:id/cancel', to: 'users#cancel', as: 'cancel'

  get 'user/show_user_profile/:id', to: 'users#show_user_profile', as: :show_user_profile

  get 'user/:id', to: 'users#show', as: :user

  get 'maps/index', as: :maps
  post '/find_nearest', to: 'maps#find_nearest', as: :find_nearest
  post '/find_nearest_friend', to: 'maps#find_nearest_friend', as: :find_nearest_friend
  post '/result', to: 'maps#result', as: :result
  get 'users/show', as: :user_show
  get 'users/sign_out', as: :user_sign_out

  get 'users/sign_in', as: :user_sign_in
  get 'users/user_profile', as: :user_profile
  get 'users/edit', as: :user_edit

  resources :users, only: [:index]
end

app/controllers/maps_controller.rb
# frozen_string_literal: true

class MapsController < ApplicationController
  before_action :authenticate_user!
  include MapsHelper

  def index
    @users = User.all_except(current_user).search(params)
  end

  def find_nearest
    @users = sort_by_distance_all(current_user)
    @nearest_person = @users.first
  end

  def find_nearest_friend
    redirect_to root_path if current_user.followers.nil?
    @users = sort_by_distance_followers(current_user)
    @nearest_friend = @users.first
  end

  def result
    @latitude = params[:latitude]
    @longitude = params[:longitude]
    @user = current_user
    @user.latitude = @latitude
    @user.longitude = @longitude
    @user.save
  end

  private

  def authenticate_user!
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/helpers/maps_helper.rb
# frozen_string_literal: true

module MapsHelper
  def sort_by_distance_all(current_user)
    User.all_except(current_user).sort_by do |user|
      Geocoder::Calculations.distance_between([current_user.latitude, current_user.longitude],
                                              [user.latitude, user.longitude])
    end
  end

  def sort_by_distance_followers(current_user)
    current_user.followers.sort_by do |user|
      Geocoder::Calculations.distance_between([current_user.latitude, current_user.longitude],
                                              [user.latitude, user.longitude])
    end
  end
end

app/views/maps/_chat_button.html.erb
<div>
    <%= link_to t(:chat), contact, class: "btn btn-outline-success formBtn", id: "chat_btn"%>
</div>

app/views/maps/_contact.html.erb
<tr id="<%= dom_id(contact) %>" data-stream-enter-class="animate-item-in" data-stream-exit-class="animate-item-out">
  <td><%= contact.full_name %></td>
  <td><%= contact.email %></td>
  <td>
  <% if button == 'Action'%>
     <%= render partial: "maps/followability_button", locals: { contact: contact }  %> 
  <% elsif button == 'Chat' %>
    <%= render partial: "maps/chat_button", locals: { contact: contact } %>
  <% end %>
  </td>
</tr>

app/views/maps/_follow_request.html.erb
<% user.follow_requests.each do |request| %>
    <%= request.followerable.email %> wants to be your friend
    <%= button_to t('maps.accept'), accept_path(request.followerable), id: "accept_id" %>
    <%= button_to t('maps.decline'), decline_path(request.followerable) %>
<% end %>

app/views/maps/_followability_button.html.erb
<% if current_user.mutual_following_with?(contact) %>
<%= button_to t('maps.delete'), unfollow_path(contact), class: "btn btn-danger formBtn" %>
<% elsif current_user.sent_follow_request_to?(contact)%>
  <%= button_to t('maps.cancel'), cancel_path(contact), class: "btn btn-outline-primary formBtn" %>
<% else %>
  <%= button_to t('maps.add'),  follow_path(contact), class: "btn btn-success formBtn" %>
<% end %>

app/views/maps/_list.html.erb
<table class="table table-zebra mt-0 w-full">
  <thead>
    <tr>
      <th class="text-left"><%= t('maps.name')%></th>
      <th class="text-left"><%= t('maps.email')%></th>
      <th class="text-left"><%= t('maps.action')%></th>
    </tr>
  </thead>
  <tbody id="contacts-list" data-controller="contacts" data-action="">
  <% contacts.each do |contact| %>
    <%= render partial: "maps/contact", locals: { contact: contact, button: "Action" }  %>
  <% end %>
  </tbody>
</table>

app/views/maps/_nearest.html.erb
<table class="table table-zebra mt-0 w-full">
  <thead>
    <tr class="w-full">
      <th class="text-left"><%= t('maps.name')%></th>
      <th class="text-left"><%= t('maps.email')%></th>
      <th class="text-left"><%= t('maps.action')%></th>
    </tr>
  </thead>
  <tbody id="nearest-person" data-controller="contacts" data-action="">
  <%= render partial: "maps/contact", locals: { contact: user, button: button } %>
  </tbody>
</table>

app/views/maps/find_nearest.turbo_stream.erb
<%= turbo_stream.update 'find-nearest-container', partial: 'nearest', locals: { user: @nearest_person, button: "Action" } %>

app/views/maps/find_nearest_friend.turbo_stream.erb
<%= turbo_stream.update 'find-nearest-friend-container', partial: 'nearest', locals: { user: @nearest_friend, button: "Chat" } %>

app/views/maps/helper.html.erb
<div class="row">
            <%= render partial: "maps/follow_request" , locals: { user: current_user }%>
                <%= form_with url: find_nearest_path do |form| %>
                    <div class="d-grid gap-2 col-2 mx-auto">
                        <%= form.submit t('maps.nearest_person'), class: "btn btn-primary" %>
                    </div>
                    <% end %>

                        <div id='find-nearest-container'></div>

                        <% if current_user.followers.count != 0%>
                            <div class="prose lg:prose-xl">
                                <%= form_with url: find_nearest_friend_path do |form| %>
                                    <div class="d-grid gap-2 col-2 mx-auto">
                                        <%= form.submit t('maps.nearest_friend'), class: "btn btn-primary" %>
                                    </div>
                                    <% end %>
                            </div>
                            <div id='find-nearest-friend-container'></div>
                            <hr />
                            <% end %>
        </div>

        <%= form_tag maps_path, method: :get, data: { turbo_frame: "search-results" , turbo_action: "advance" } do |f|%>
            <div class="d-grid gap-2 col-6 mx-auto">
                <%= text_field_tag :query, nil, placeholder: "Search user" , class: "input input-bordered " %>
                    <%= submit_tag t('search'), class: "btn btn-primary" %>
            </div>
            <% end %>

                <div class="bg-gray-100 p-8 col-span-5">
                    <%= turbo_frame_tag "search-results" do %>
                        <%= render partial: "maps/list" , locals: { contacts: @users } %>
                            <% end %>
                </div>

app/views/maps/index.html.erb
<script type="text/javascript">
    ymaps.ready(init);
    var MyMap;

    function init() {
        myMap = new ymaps.Map('ymap', {
            center: [55.76, 37.64],
            zoom: 10
        });

        myMap.controls.remove('searchControl');
        myMap.controls.remove('trafficControl');
        myMap.controls.remove('typeSelector');
        myMap.controls.remove('fullscreenControl');
        myMap.controls.remove('rulerControl');
        myMap.controls.remove('miniMap');

        let geolocation = ymaps.geolocation;

        geolocation.get({
            provider: 'browser',
            mapStateAutoApply: true
        }).then(function (result) {
            result.geoObjects.options.set('preset', 'islands#blueCircleIcon');
            result.geoObjects.get(0).properties.set({
                balloonContentBody: 'Moe местоположение'
            });
            document.getElementById('latitude').value = result.geoObjects.get(0).geometry.getCoordinates()[0];
            document.getElementById('longitude').value = result.geoObjects.get(0).geometry.getCoordinates()[1];
            document.getElementById('Update').click();
            myMap.geoObjects.add(result.geoObjects);
        });

        myMap.copyrights.add('© 2022 Иван Погиба');
        show_users(<%= current_user.followers.count %>);
    }

    function show_users(length) {
        for (let i = 0; i < length; i++) {
            latitude = document.getElementById('user-latitude-' + i).textContent;
            longitude = document.getElementById('user-longitude-' + i).textContent;
            email = document.getElementById('user-email-' + i).textContent;
            updated_at = document.getElementById('user-updated_at-' + i).textContent;
            avatar = document.getElementById('user-avatar-' + i);
            id = document.getElementById('user-id-' + i).textContent;
            myPlacemark = new ymaps.Placemark([parseFloat(latitude), parseFloat(longitude)], {
                balloonContentHeader: '<a href = "/user/show_user_profile/' + id + '">' + email + '</a><br>',
                balloonContentBody: avatar.innerHTML + '<br>' +
                    '<b>Последний раз заходил в ' + updated_at + '</b> <br/>',
                // hintContent: name
            },
                {
                    iconLayout: 'default#image',
                    iconImageHref: avatar.getElementsByTagName("img")[0].getAttribute("src"),
                    iconImageSize: [40, 40],
                    iconImageOffset: [-5, -38]
                }
            );

            myMap.geoObjects.add(myPlacemark);
        }
    }

</script>
<div class="row">
    <div class="col-9" style="margin: 0; padding: 0;">
        <div id="ymap" class="map"></div>
    </div>

    <div class="col-3" style="margin: 0; padding: 0;">

        <div class="container py-1">
            <div class="row">
                <div class="card-body text-center">
                        <%= image_tag(current_user.avatar_thumbnail, size: "96x96" , style: "width: 150px;" ,
                            class: "rounded-circle img-fluid" ) %>
                                        <h5 class="my-3">
                                            <%= current_user.full_name %>
                                        </h5>
                                        <p class="text-muted mb-1">
                                            <%= current_user.email %>
                                        </p>
                                        <p class="text-muted mb-4">
                                            <%= t('maps.last_update', time: time_ago_in_words(current_user.updated_at)) %>
                                        </p>
                </div>
            </div>
        </div>
        <hr>
                    <% current_user.follow_requests.each do |request| %>
                      <%= t('maps.want_to_be_your_friend', name: request.followerable.full_name) %>
                      <div class="mt-2">
                      <div class="d-inline-block">
                        <%= button_to t(:accept), accept_path(request.followerable), id: "accept_id", class: 'btn btn-primary btn-sm' %>
                      </div>
                    <div class="d-inline-block ms-2"><%= button_to t(:decline), decline_path(request.followerable), class: 'btn btn-danger btn-sm' %></div>
                        </div>
                    <hr>
                    <% end %>

            <div class="container text-center py-1">
                <%= form_with url: find_nearest_path do |form| %>
                    <%= form.submit t('maps.nearest_person'), class: "btn btn-primary" %>
                <% end %>
                <div id='find-nearest-container'></div>
            </div>
                <hr>
            <div class="text-center">
                    <% if current_user.followers.count !=0%>
                            <div class="prose lg:prose-xl mb-4">
                                <%= form_with url: find_nearest_friend_path do |form| %>
                                    <%= form.submit t('maps.nearest_firend') , class: "btn btn-primary" %>
                                <% end %>
                            </div>
                            <% end %>
                <div id='find-nearest-friend-container'></div>
        <div class="container">
            <%= form_tag maps_path, method: :get, data: { turbo_frame: "search-results" , turbo_action: "advance" } do |f|%>
                <div class="input-group">
                    <%= text_field_tag :query, nil, placeholder: "Search user" , class: "form-control" %>
                    <%= submit_tag t(:search) , class: "btn btn btn-primary", id: "search_id" %>
                </div>
            <% end %>
            <%= turbo_frame_tag "search-results" do %>
            <%= render partial: "maps/list" , locals: { contacts: @users } %>
            <% end %>
            </div>
        </div>
    </div>

</div>
</div>
<div id="users" style="display: none;">
    <% current_user.followers.each_with_index do |user, index|%>
        <p id="user-email-<%=index%>">
            <%= user.email %>
        </p>
        <p id="user-latitude-<%=index%>">
            <%= user.latitude%>
        </p>
        <p id="user-longitude-<%=index%>">
            <%= user.longitude%>
        </p>
        <p id="user-updated_at-<%=index%>">
            <%= user.updated_at%>
        </p>
        <p id="user-id-<%=index%>">
            <%= user.id%>
        </p>
        <p id="user-avatar-<%=index%>">
            <%= image_tag(user.avatar, size:"96x96")%>
        <%end%>
</div>
</div>

<%= form_with url: result_path do |f| %>
    <div style="display: none">
        <%= f.text_field :latitude, id: :latitude %>
            <%= f.text_field :longitude, id: :longitude %>
                <%= f.submit t('maps.update_geolocation') , id: "Update" , class: "btn btn-primary" %>
    </div>
    <%end%>