config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'maps#index'

  resources :rooms do
    resources :messages
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'users', to: 'devise/sessions#new'
  end

  post 'user/:id/', to: 'users#create'
  post 'user/:id/follow', to: 'users#follow', as: 'follow'
  post 'user/:id/unfollow', to: 'users#unfollow', as: 'unfollow'
  post 'user/:id/accept', to: 'users#accept', as: 'accept'
  post 'user/:id/decline', to: 'users#decline', as: 'decline'
  post 'user/:id/cancel', to: 'users#cancel', as: 'cancel'

  get 'user/show_user_profile/:id', to: 'users#show_user_profile', as: :show_user_profile

  get 'user/:id', to: 'users#show', as: :user

  get 'maps/index', as: :maps
  post '/find_nearest', to: 'maps#find_nearest', as: :find_nearest
  post '/find_nearest_friend', to: 'maps#find_nearest_friend', as: :find_nearest_friend
  post '/result', to: 'maps#result', as: :result
  get 'users/show', as: :user_show
  get 'users/sign_out', as: :user_sign_out

  get 'users/sign_in', as: :user_sign_in
  get 'users/user_profile', as: :user_profile
  get 'users/edit', as: :user_edit

  resources :users, only: [:index]
end

app/models/user.rb
# frozen_string_literal: true

require 'open-uri'

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2 github]

  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to 'users' }
  has_many :messages
  has_one_attached :avatar
  after_commit :add_default_avatar, on: %i[create update]
  followability

  validates :email, presence: { message: 'не может быть пустым' },
                    uniqueness: { message: 'такой аккаунт уже зарегистрирован' }
  # validates_numericality_of :latitude,
  #                           greater_than_or_equal_to: -90,
  #                           message: 'ширина должна быть в диапазоне от -90 до 90'

  # validates_numericality_of :latitude,
  #                           greater_than_or_equal_to: 90,
  #                           message: 'ширина должна быть в диапазоне от -90 до 90'

  # validates_numericality_of :longitude,
  #                           greater_than_or_equal_to: -180,
  #                           message: 'ширина должна быть в диапазоне от -180 до 180'

  # validates_numericality_of :latitude,
  #                           greater_than_or_equal_to: 180,
  #                           message: 'ширина должна быть в диапазоне от -180 до 180'

  def unfollow(user)
    followerable_relationships.where(followable_id: user.id).destroy_all
  end

  def self.search(params)
    if params[:query].blank?
      none
    else
      where(
        'full_name LIKE ?', "%#{sanitize_sql_like(params[:query])}%"
      )
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.full_name = auth.info.name
      user.avatar_url = auth.info.image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.from_omniauth_github(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first
    user ||= User.create(
      full_name: data['name'],
      email: data['email'],
      password: Devise.friendly_token[0, 20],
      avatar_url: data['image'],
      provider: access_token.provider,
      uid: access_token.uid
    )
    user
  end

  def avatar_thumbnail
    avatar.variant(resize_to_limit: [150, 150]).processed
  end

  def chat_avatar
    avatar.variant(resize_to_limit: [50, 50]).processed
  end

  private

  def add_default_avatar
    unless avatar.attached?
      avatar.attach(
        io: File.open(Rails.root.join('app', 'assets', 'images', 'no-photo.png')),
        filename: 'no-photo.png',
        content_type: 'image/png'
      )
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # def twitter
    # end

    def google_oauth2
      user = User.from_omniauth(auth)
      if user.present?
        sign_out_all_scopes
        flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect user, event: :authentication # this will throw if @user is not activated
      else
        flash[:alert] =
          t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: user.errors.full_messages.to_sentence.to_s
        redirect_to new_user_session_path
      end
    end

    def github
      user = User.from_omniauth_github(request.env['omniauth.auth'])

      if user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Github'
        sign_in_and_redirect user, event: :authentication
      else
        session['devise.github_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
        redirect_to new_user_session_path, alert: user.errors.full_messages.join("\n")
      end
    end

    # More info at:
    # https://github.com/heartcombo/devise#omniauth

    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end

    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end

    # protected

    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
    private

    def auth
      @auth ||= request.env['omniauth.auth']
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]
    before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: %i[avatar full_name])
    end

    # If you have extra params to permit, append them to the sanitizer.
    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: %i[avatar full_name])
    end

    protected

    def update_resource(resource, params)
      if current_user.provider == 'google_oauth2' || current_user.provider == 'github'
        params.delete('current_password')
        resource.update_without_password(params)
      else
        resource.update_with_password(params)
      end
    end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    def after_sign_out_path_for(_resource_or_scope)
      new_user_session_path
    end

    def after_sign_in_path_for(resource_or_scope)
      stored_location_for(resource_or_scope) || root_path
    end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show follow unfollow accept decline cancel]
  def index
    @users = User.all_except(current_user)
  end

  def follow
    @users = current_user.followers
    current_user.send_follow_request_to(@user)
    redirect_back fallback_location: root_path
  end

  def unfollow
    make_it_an_unfriend_request
    current_user.unfollow(@user)
    redirect_back fallback_location: root_path
  end

  def accept
    current_user.accept_follow_request_of(@user)
    make_it_a_friend_request
    redirect_back fallback_location: root_path
  end

  def decline
    current_user.decline_follow_request_of(@user)
    redirect_back fallback_location: root_path
  end

  def cancel
    current_user.remove_follow_request_for(@user)
    redirect_back fallback_location: root_path
  end

  def show
    @user = User.find(params[:id])
    @users = current_user.followers

    @room = Room.new
    @rooms = Room.public_rooms
    @room_name = get_name(@user, current_user)
    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, current_user], @room_name)

    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)
    render 'rooms/index'
  end

  def show_user_profile
    @user = User.find(params[:id])
    redirect_to user_profile_path if @user == current_user
  end

  def user_profile
    @user = current_user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def make_it_a_friend_request
    current_user.send_follow_request_to(@user)
    @user.accept_follow_request_of(current_user)
  end

  def make_it_an_unfriend_request
    @user.unfollow(current_user) if @user.mutual_following_with?(current_user)
  end

  def get_name(user1, user2)
    user = [user1, user2].sort
    "private_#{user[0].id}_#{user[1].id}"
  end
end

app/views/users/_user.html.erb
<% if @single_room && @single_room.participant?(@single_room, user) %>
  <% isActive = 'active' %>
<% else %>
  <% isActive = '' %>
<% end %>
<li class="list-group-item d-flex align-items-center justify-content-between user_list_item <%= isActive %>">
  <div>
    <%= link_to image_tag(user.chat_avatar, class: 'chat_pfp'), user %>
  </div>
  <%= link_to user.full_name, user, class:'ms-2 me-auto username', data: {turbo: "false"}, id: "#{dom_id(user)}" %>
</li>

app/views/users/show_user_profile.html.erb
<body style="background-color: #eee;">
<section style="background-color: #eee;">
    <div class="container py-5">
      <div class="row">
        <div class="col-lg-4">
          <div class="card mb-4">
            <div class="card-body text-center">
            <%= image_tag(@user.avatar_thumbnail, size: "96x96" , style: "width: 150px;" ,
                            class: "rounded-circle img-fluid" ) %>
              <h5 class="my-3"><%= @user.full_name %></h5>
              <p class="text-muted mb-1"></p>
              <p class="text-muted mb-4"><%= t('maps.last_update', time: time_ago_in_words(current_user.updated_at)) %></p>
              <div class="d-flex justify-content-center mb-2">
              <% if current_user.mutual_following_with?(@user)%>
                <%= link_to "Chat", @user, class: 'btn btn-primary' %>
              <% else %>
                <%= render partial: "maps/followability_button", locals: { contact: @user }  %>
              <% end %> 
              </div>
            </div>
          </div>
          <div class="card mb-4 mb-lg-0">
            <div class="card-body p-0">
              <ul class="list-group list-group-flush rounded-3">
              <% @user.followers.each do |friend| %>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <p class="mb-0"> <%= link_to friend.full_name, "/user/show_user_profile/" + friend.id.to_s, id: "#{dom_id(friend)}" %></p>
                  <span class="badge bg-primary rounded-pill"><%= friend.followers.count %></span>
                </li>
              <% end %>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-8">
          <div class="card mb-4">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0"><%=t(:full_name)%></p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0"><%= @user.full_name %></p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0"><%=t(:email)%></p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0"><%= @user.email %></p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0"><%=t(:since)%></p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0"><%= time_ago_in_words(@user.created_at) %></p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0"><%=t(:location)%></p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0"><%= Geocoder.search([@user.latitude.to_f, @user.longitude.to_f]).first.address %></p>
                </div>
              </div>
            </div>
          </div>
              <div class="card mb-4 mb-md-0">
                <div class="card-body">
                  <p class="mb-4"><span class="text-primary font-italic me-1"><%= t('maps.action') %></span></p>
                  <div class="d-flex flex-row-reverse">
                      <%= link_to 'Back', url_for(:back), class: "p-2 btn btn-primary active", style: "margin: 0 0 0 30px;" %>
                      <% if current_user.mutual_following_with?(@user)%>  
                      <%= turbo_stream_from @user %>
                      <div id="<%= dom_id(@user) %>">
                        <%= render partial: "maps/followability_button", locals: { contact: @user }  %>
                      </div>
                      <% end %>
                  </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  </section>
</body>

app/views/users/user_profile.html.erb
<body style="background-color: #eee;">
<section style="background-color: #eee;">
    <div class="container py-5">

      <div class="row">
        <div class="col-lg-4">
          <div class="card mb-4">
            <div class="card-body text-center">
            <%= image_tag(current_user.avatar_thumbnail, size: "96x96" , style: "width: 150px;" ,
                            class: "rounded-circle img-fluid" ) %>
              <h5 class="my-3"><%= @user.full_name %></h5>
              <p class="text-muted mb-1"></p>
              <p class="text-muted mb-4"><%= t('maps.last_update', time: time_ago_in_words(current_user.updated_at)) %></p>
              <div class="d-flex justify-content-center mb-2">
                <%= link_to t(:edit_profile), user_edit_path, class: 'btn btn-primary' %> 
              </div>
            </div>
          </div>
          <div class="card mb-4 mb-lg-0">
            <div class="card-body p-0">
              <ul class="list-group list-group-flush rounded-3">
              <% current_user.followers.each do |friend| %>
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <p class="mb-0"> <%= link_to friend.full_name, "/user/show_user_profile/" + friend.id.to_s, id: "#{dom_id(friend)}" %></p>
                  <span class="badge bg-primary rounded-pill"><%= friend.followers.count %></span>

                </li>
              <% end %>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-8">
          <div class="card mb-4">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0"><%=t(:full_name)%></p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0"><%= @user.full_name %></p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0"><%=t(:email)%></p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0"><%= @user.email %></p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0"><%=t(:since)%></p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0"><%= time_ago_in_words(@user.created_at) %></p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0"><%=t(:location)%></p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0"><%= Geocoder.search([@user.latitude.to_f, @user.longitude.to_f]).first.address %></p>
                </div>
              </div>
            </div>
          </div>
              <div class="card mb-4 mb-md-0">
                <div class="card-body">
                  <p class="mb-4"><span class="text-primary font-italic me-1"><%=t(:friends_requests)%></span>
                  </p>
                  <% if current_user.follow_requests.count == 0 %>
                  <p class="mb-1" style="font-size: .77rem;"><%= t(:not_have_any_requests)%></p>
                  <div class="progress rounded" style="height: 5px;">
                    <div class="progress-bar" role="progressbar" style="width: 100%" aria-valuenow="100"
                      aria-valuemin="0" aria-valuemax="100"></div>
                  </div>
                  <% else %>
                  <div class="row">
                    <% current_user.follow_requests.each do |request| %>
                    <div class="col-9">
                      <%= t('maps.want_to_be_your_friend', name: request.followerable.full_name) %>
                    </div>
                    <div class="col-1">
                      <%= button_to t('maps.accept'), accept_path(request.followerable), class: 'btn btn-primary btn-sm' %>
                    </div>
                    <div class="col-1">
                      <%= button_to t('maps.decline'), decline_path(request.followerable), class: 'btn btn-danger btn-sm'  %>
                    </div>
                    <% end %>
                  <% end %>
                  </div>
                </div>
              </div>
        </div>
      </div>
    </div>
  </section>
</body>