config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'maps#index'

  resources :rooms do
    resources :messages
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :user do
    get 'users', to: 'devise/sessions#new'
  end

  post 'user/:id/', to: 'users#create'
  post 'user/:id/follow', to: 'users#follow', as: 'follow'
  post 'user/:id/unfollow', to: 'users#unfollow', as: 'unfollow'
  post 'user/:id/accept', to: 'users#accept', as: 'accept'
  post 'user/:id/decline', to: 'users#decline', as: 'decline'
  post 'user/:id/cancel', to: 'users#cancel', as: 'cancel'

  get 'user/show_user_profile/:id', to: 'users#show_user_profile', as: :show_user_profile

  get 'user/:id', to: 'users#show', as: :user

  get 'maps/index', as: :maps
  post '/find_nearest', to: 'maps#find_nearest', as: :find_nearest
  post '/find_nearest_friend', to: 'maps#find_nearest_friend', as: :find_nearest_friend
  post '/result', to: 'maps#result', as: :result
  get 'users/show', as: :user_show
  get 'users/sign_out', as: :user_sign_out

  get 'users/sign_in', as: :user_sign_in
  get 'users/user_profile', as: :user_profile
  get 'users/edit', as: :user_edit

  resources :users, only: [:index]
end

app/views/layouts/_flash.html.erb
<div class="container">
    <% flash.each do |type, msg| %>
      <div class='alert alert-primary alert-dismissible' role="alert">
        <%= msg %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <% end %>
    </div>
  </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light"> 
  <div class="container-fluid">
  <% if current_user %>
    <%= link_to "Maply", maps_path, class: 'navbar-brand', id: 'root'%>
  <% else %>
    <%= link_to "Maply", new_user_session_path, class: 'navbar-brand', id: 'sign_in_lnk'%>
  <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
          <% if current_user %>
        <li class="nav-item">
          <%= link_to t(:log_out), destroy_user_session_path, class: 'nav-link', id: 'log_out', 'data-turbo-method': :delete %>
        </li>
        <li class="nav-item">
          <%= link_to t(:edit_profile), edit_user_registration_path, class: 'nav-link', id: 'edit_profile', 'data-turbo-method': :update %>
        </li>
        <li class="nav-item">
          <%= link_to t(:show_profile), user_profile_path, class: 'nav-link', id: 'show_profile', 'data-turbo-method': :user_profile %>
        </li>
        <li class="nav-item">
          <%= link_to t(:chat), rooms_path, class: 'nav-link', id: 'chat', 'data-turbo-method': :show %>
        </li>
          <% else %>
        <li class="nav-item">
          <%= link_to t(:sign_up), new_user_registration_path, id: 'sign_up', class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to t(:log_in), new_user_session_path, id: 'log_in', class: 'nav-link' %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div id="flash" style="position:absolute; z-index: 2; right: 10px;">
          <%= render partial: "layouts/flash" %>
        </div>
</nav>

app/views/layouts/_new_message_form.html.erb
<div class="form-grousp msg-form">
    <%= form_with(model: [@single_room, @message], remote: true, class:'d-flex',
    data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset"}) do |f|%>
        <%= f.text_field :body, id: 'chat-text', class: 'form-control msg-content', autocomplete: 'off'%>
        <%= f.submit "Send", data: {disable_with: false}, class: 'btn btn-primary'%>
</div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Map</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://api-maps.yandex.ru/2.1/?apikey=<%=Rails.application.credentials[:yandex_maps_api_key]%>&lang=ru_RU" type="text/javascript"></script>
    <script
      src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js"
      defer
    ></script>
    
  <style>
      <%= ".msg-#{current_user&.id}" %> {
      background-color: #007bff !important;
      padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
      display: flex;
        justify-content: flex-end
      }
    </style>

  </head>
  <body>

<%= render partial: "layouts/navbar" %>
    <%= yield %>
  </body>
</html>